package pl.mbrzozowski.ranger.giveaway;

public enum GiveawayGeneratorStage {
    TIME_MODE,
    TIME_MODE_NOT_SELECTED,
    DATE_SELECT,
    DATE_NOT_SELECTED,
    TIME_SELECT,
    TIME_NOT_SELECTED,
    TIME_DURATION,
    TIME_DURATION_NOT_SELECTED,
    PRIZE,
    PING,
    RULES,
    PRIZE_QTY_NOT_CORRECT,
    PRIZE_REMOVE,
    MAX_NUMBER_OF_PRIZE_STAGE,
    CLAN_MEMBER_EXCLUDE,
    CLAN_MEMBER_EXCLUDE_NOT_SELECTED,
    END,
    UNEXPECTED_ERROR,
    CANNOT_END,
    RULES_NOT_CORRECT,
    CANCEL
}
